version: "3.7"
services:
  redis:
    image: redis:alpine
    restart: on-failure
    ports:
      - "6379:6379"
  postgres:
    image: postgres:14-alpine
    env_file:
      - ./.env
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: on-failure
    ports:
      - "5432:5432"
  bot:
    build: .
    command: sh -c "alembic upgrade head && python -m main"
    restart: always
    depends_on:
      - postgres
      - redis


volumes:
  pgdata:
